<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tad</string>
	</array>
	<key>limitLineLength</key>
	<false/>
	<key>name</key>
	<string>TAD</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#conditionals</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants_aux</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#arrays</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#cross_symbol</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#right_arrow_symbol</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.tad</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.tad</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.tad</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.tad</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Declaraciones de TADs auxiliares</string>
			<key>match</key>
			<string>((?:w*TAD*?))( .*? )(es|ES)( .*?(?=( |
|&lt;|\(|{)))</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;|\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.parens.begin.tad</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Highligting para Tupla&lt;...&gt; en declaraciones</string>
			<key>end</key>
			<string>&gt;|\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.parens.end.tad</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.angle-brackets</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[A-Z].*?( |(?=\)))</string>
					<key>name</key>
					<string>storage.modifier.tad</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.tad</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.tad</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.tad</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Declaracion de TAD principal</string>
			<key>match</key>
			<string>((?:w*TAD*?))( .*?\((.*?(?=\))).*?\)| .*?
)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.tad</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.other.tad</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.tad</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Seccion Extiende del header</string>
			<key>match</key>
			<string>(?i)(w*(EXTIENDE)( |:|	|
))( .*?\((.*?(?=\))).*?\))</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Palabras clave de los TADS</string>
			<key>match</key>
			<string>(?i)(w*(?:EXPORTA|IMPORTA|par[a,á]metros formales|g[e,é]neros|GENERADORES|Observadores B[a,á]sicos|OBSERVADORES|Otras Operaciones|Otras Op|OtrasOp|USA|GEN|OBS)( |:|	|
))</string>
			<key>name</key>
			<string>keyword.operator.tad</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)(w*(?:Igualdad Observacional|IgObs|Ig Obs)( |:|\t|\n))</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.tad</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Seccion de Igualdad observacional</string>
			<key>end</key>
			<string>((;))|(?i)(w*(?=EXTIENDE|EXPORTA|IMPORTA|g[e,é]neros|GENERADORES|Observadores B[a,á]sicos|OBSERVADORES|USA|usa|Usa|GEN|gen|Gen|OBS|obs|Obs))</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.line.tad.tad</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants_aux</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arrays</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#equal_obs_symbol</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#iff_symbol</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#logic_symbols</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)w*AXIOMAS( |:|	|
)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.tad</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Parte de Axiomas</string>
			<key>end</key>
			<string>Fin TAD</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.tad</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>".*?"</string>
					<key>name</key>
					<string>string.quoted.double.tad</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#conditionals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#logic_symbols</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arrays</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants_aux</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#equal_symbol</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.tad</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Atributos para los tipo Tupla</string>
					<key>match</key>
					<string>(?:\..*?)([a-z]+)</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Aridad de Funciones (Nombre de funcion)</string>
			<key>match</key>
			<string>(^(?:		| {8}))(?!//)([A-zÀ-ú0-9_?#ñØ\+•·\-≤ ]+:)</string>
			<key>name</key>
			<string>entity.name.function.tad</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.conditional.tad</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Llaves para restricciones</string>
			<key>end</key>
			<string>}
|(?=//)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.conditional.tad</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants_aux</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arrays</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#equal_symbol</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#iff_symbol</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#logic_symbols</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Llave si hay comentario</string>
					<key>match</key>
					<string>}(.*?)(?=//)</string>
					<key>name</key>
					<string>keyword.control.conditional.tad</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>arrays</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.brackets.begin.tad</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Arrays</string>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.brackets.end.tad</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^([0-9]+?)(?=\])</string>
					<key>name</key>
					<string>constant.numeric.tad</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>es necesario cuando hay una funcion adentro</string>
					<key>match</key>
					<string>\[</string>
					<key>name</key>
					<string>keyword.control.conditional.tad</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#conditionals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#logic_symbols</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants_aux</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#functions_symbols</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>comment</key>
			<string>Comentario del codigo</string>
			<key>match</key>
			<string>//.*$</string>
			<key>name</key>
			<string>comment.line.tad</string>
		</dict>
		<key>conditionals</key>
		<dict>
			<key>comment</key>
			<string>Palabras clave del tipo Bool</string>
			<key>match</key>
			<string>(?i)((	| |
)(IF|FI|ELSE|ELIF|THEN)(	| |
))</string>
			<key>name</key>
			<string>keyword.control.conditional.tad</string>
		</dict>
		<key>constants</key>
		<dict>
			<key>comment</key>
			<string>Constantes</string>
			<key>match</key>
			<string>(?i)(\b(true|false|none|Ø|nil|[0-9])\b)</string>
			<key>name</key>
			<string>constant.language.tad</string>
		</dict>
		<key>constants_aux</key>
		<dict>
			<key>comment</key>
			<string>Constante &lt;&gt;</string>
			<key>match</key>
			<string>&lt;&gt;</string>
			<key>name</key>
			<string>constant.language.tad</string>
		</dict>
		<key>cross_symbol</key>
		<dict>
			<key>comment</key>
			<string>Highligting para signo "x"</string>
			<key>match</key>
			<string>(?: |	)(?:x|×)(?: |	)</string>
			<key>name</key>
			<string>variable.language.tad</string>
		</dict>
		<key>equal_obs_symbol</key>
		<dict>
			<key>comment</key>
			<string>Highligting para signo "=obs"</string>
			<key>match</key>
			<string>( |	)(=obs)(?=( |	))</string>
			<key>name</key>
			<string>variable.language.tad</string>
		</dict>
		<key>equal_symbol</key>
		<dict>
			<key>comment</key>
			<string>Highligting para signo "="</string>
			<key>match</key>
			<string>( |	|
)(=|≡)(?=( |	))</string>
			<key>name</key>
			<string>variable.language.tad</string>
		</dict>
		<key>functions</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tad</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Highligting de nombres de funciones varias</string>
			<key>match</key>
			<string>(?:\(| |	|\+|-|)([A-zÀ-ú0-9_?#ñØ]+?)(?=(\(| \())</string>
		</dict>
		<key>functions_symbols</key>
		<dict>
			<key>comment</key>
			<string>Simbolos de funciones de los TADs basicos</string>
			<key>match</key>
			<string>(•|◦|\+|\-|β|π|≤|≥|&amp;|⊂|⊆|∈|∩|∪|←)</string>
			<key>name</key>
			<string>entity.name.tad</string>
		</dict>
		<key>iff_symbol</key>
		<dict>
			<key>comment</key>
			<string>Highligting para signo "&lt;=&gt;"</string>
			<key>match</key>
			<string>(?:↔|&lt;=&gt;|&lt;\-&gt;|⇔|⇐⇒)</string>
			<key>name</key>
			<string>variable.language.tad</string>
		</dict>
		<key>logic_symbols</key>
		<dict>
			<key>comment</key>
			<string>Simbolos de funciones condicionales</string>
			<key>match</key>
			<string>(⇒|=&gt;)L|(∨L|∧L|∨|∧|¬|(∀.*?:)|∀|∃|∄|⇒|=&gt;|⇐|&lt;=)</string>
			<key>name</key>
			<string>keyword.control.conditional.tad</string>
		</dict>
		<key>right_arrow_symbol</key>
		<dict>
			<key>comment</key>
			<string>Highligting para signo "-&gt;"</string>
			<key>match</key>
			<string>((?:-&gt;|↦|→))</string>
			<key>name</key>
			<string>variable.language.tad</string>
		</dict>
		<key>strings</key>
		<dict>
			<key>comment</key>
			<string>Strings (palabras entre comillas)</string>
			<key>match</key>
			<string>".*?"</string>
			<key>name</key>
			<string>string.quoted.double.tad</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.tad</string>
</dict>
</plist>
